// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusanscondensedboldoblique provides the "DejaVuSansCondensed BoldOblique" TrueType font
// from the DejaVu font family.
package dejavusanscondensedboldoblique // import "github.com/go-fonts/dejavu/dejavusanscondensedboldoblique"

import _ "embed"

// TTF is the data for the "DejaVuSansCondensed BoldOblique" TrueType font.
//
//go:embed DejaVuSansCondensed-BoldOblique.ttf
var TTF []byte
