// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavuserif provides the "DejaVuSerif" TrueType font
// from the DejaVu font family.
package dejavuserif // import "github.com/go-fonts/dejavu/dejavuserif"

import _ "embed"

// TTF is the data for the "DejaVuSerif" TrueType font.
//
//go:embed DejaVuSerif.ttf
var TTF []byte
