// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusansmonooblique provides the "DejaVuSansMono Oblique" TrueType font
// from the DejaVu font family.
package dejavusansmonooblique // import "github.com/go-fonts/dejavu/dejavusansmonooblique"

import _ "embed"

// TTF is the data for the "DejaVuSansMono Oblique" TrueType font.
//
//go:embed DejaVuSansMono-Oblique.ttf
var TTF []byte
