// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusanscondensedbold provides the "DejaVuSansCondensed Bold" TrueType font
// from the DejaVu font family.
package dejavusanscondensedbold // import "github.com/go-fonts/dejavu/dejavusanscondensedbold"

import _ "embed"

// TTF is the data for the "DejaVuSansCondensed Bold" TrueType font.
//
//go:embed DejaVuSansCondensed-Bold.ttf
var TTF []byte
