// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavuserifcondensed provides the "DejaVuSerifCondensed" TrueType font
// from the DejaVu font family.
package dejavuserifcondensed // import "github.com/go-fonts/dejavu/dejavuserifcondensed"

import _ "embed"

// TTF is the data for the "DejaVuSerifCondensed" TrueType font.
//
//go:embed DejaVuSerifCondensed.ttf
var TTF []byte
