// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavuserifbold provides the "DejaVuSerif Bold" TrueType font
// from the DejaVu font family.
package dejavuserifbold // import "github.com/go-fonts/dejavu/dejavuserifbold"

import _ "embed"

// TTF is the data for the "DejaVuSerif Bold" TrueType font.
//
//go:embed DejaVuSerif-Bold.ttf
var TTF []byte
