// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavuserifcondensedbolditalic provides the "DejaVuSerifCondensed BoldItalic" TrueType font
// from the DejaVu font family.
package dejavuserifcondensedbolditalic // import "github.com/go-fonts/dejavu/dejavuserifcondensedbolditalic"

import _ "embed"

// TTF is the data for the "DejaVuSerifCondensed BoldItalic" TrueType font.
//
//go:embed DejaVuSerifCondensed-BoldItalic.ttf
var TTF []byte
