// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusanscondensed provides the "DejaVuSansCondensed" TrueType font
// from the DejaVu font family.
package dejavusanscondensed // import "github.com/go-fonts/dejavu/dejavusanscondensed"

import _ "embed"

// TTF is the data for the "DejaVuSansCondensed" TrueType font.
//
//go:embed DejaVuSansCondensed.ttf
var TTF []byte
