// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavumathtexgyre provides the "DejaVuMathTeXGyre" TrueType font
// from the DejaVu font family.
package dejavumathtexgyre // import "github.com/go-fonts/dejavu/dejavumathtexgyre"

import _ "embed"

// TTF is the data for the "DejaVuMathTeXGyre" TrueType font.
//
//go:embed DejaVuMathTeXGyre.ttf
var TTF []byte
