// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavuserifcondenseditalic provides the "DejaVuSerifCondensed Italic" TrueType font
// from the DejaVu font family.
package dejavuserifcondenseditalic // import "github.com/go-fonts/dejavu/dejavuserifcondenseditalic"

import _ "embed"

// TTF is the data for the "DejaVuSerifCondensed Italic" TrueType font.
//
//go:embed DejaVuSerifCondensed-Italic.ttf
var TTF []byte
