// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavuserifcondensedbold provides the "DejaVuSerifCondensed Bold" TrueType font
// from the DejaVu font family.
package dejavuserifcondensedbold // import "github.com/go-fonts/dejavu/dejavuserifcondensedbold"

import _ "embed"

// TTF is the data for the "DejaVuSerifCondensed Bold" TrueType font.
//
//go:embed DejaVuSerifCondensed-Bold.ttf
var TTF []byte
