// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavuserifbolditalic provides the "DejaVuSerif BoldItalic" TrueType font
// from the DejaVu font family.
package dejavuserifbolditalic // import "github.com/go-fonts/dejavu/dejavuserifbolditalic"

import _ "embed"

// TTF is the data for the "DejaVuSerif BoldItalic" TrueType font.
//
//go:embed DejaVuSerif-BoldItalic.ttf
var TTF []byte
