// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusansmono provides the "DejaVuSansMono" TrueType font
// from the DejaVu font family.
package dejavusansmono // import "github.com/go-fonts/dejavu/dejavusansmono"

import _ "embed"

// TTF is the data for the "DejaVuSansMono" TrueType font.
//
//go:embed DejaVuSansMono.ttf
var TTF []byte
