// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusansoblique provides the "DejaVuSans Oblique" TrueType font
// from the DejaVu font family.
package dejavusansoblique // import "github.com/go-fonts/dejavu/dejavusansoblique"

import _ "embed"

// TTF is the data for the "DejaVuSans Oblique" TrueType font.
//
//go:embed DejaVuSans-Oblique.ttf
var TTF []byte
