// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusanscondensedoblique provides the "DejaVuSansCondensed Oblique" TrueType font
// from the DejaVu font family.
package dejavusanscondensedoblique // import "github.com/go-fonts/dejavu/dejavusanscondensedoblique"

import _ "embed"

// TTF is the data for the "DejaVuSansCondensed Oblique" TrueType font.
//
//go:embed DejaVuSansCondensed-Oblique.ttf
var TTF []byte
