// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusansextralight provides the "DejaVuSans ExtraLight" TrueType font
// from the DejaVu font family.
package dejavusansextralight // import "github.com/go-fonts/dejavu/dejavusansextralight"

import _ "embed"

// TTF is the data for the "DejaVuSans ExtraLight" TrueType font.
//
//go:embed DejaVuSans-ExtraLight.ttf
var TTF []byte
