// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusansmonoboldoblique provides the "DejaVuSansMono BoldOblique" TrueType font
// from the DejaVu font family.
package dejavusansmonoboldoblique // import "github.com/go-fonts/dejavu/dejavusansmonoboldoblique"

import _ "embed"

// TTF is the data for the "DejaVuSansMono BoldOblique" TrueType font.
//
//go:embed DejaVuSansMono-BoldOblique.ttf
var TTF []byte
