// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusansmonobold provides the "DejaVuSansMono Bold" TrueType font
// from the DejaVu font family.
package dejavusansmonobold // import "github.com/go-fonts/dejavu/dejavusansmonobold"

import _ "embed"

// TTF is the data for the "DejaVuSansMono Bold" TrueType font.
//
//go:embed DejaVuSansMono-Bold.ttf
var TTF []byte
