// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavusansboldoblique provides the "DejaVuSans BoldOblique" TrueType font
// from the DejaVu font family.
package dejavusansboldoblique // import "github.com/go-fonts/dejavu/dejavusansboldoblique"

import _ "embed"

// TTF is the data for the "DejaVuSans BoldOblique" TrueType font.
//
//go:embed DejaVuSans-BoldOblique.ttf
var TTF []byte
