// generated by go run gen-fonts.go; DO NOT EDIT

// Package dejavuserifitalic provides the "DejaVuSerif Italic" TrueType font
// from the DejaVu font family.
package dejavuserifitalic // import "github.com/go-fonts/dejavu/dejavuserifitalic"

import _ "embed"

// TTF is the data for the "DejaVuSerif Italic" TrueType font.
//
//go:embed DejaVuSerif-Italic.ttf
var TTF []byte
